#pragma config(Motor,  port2,           LeftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           RightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           ArmMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
const bool on = true;
int thresh = 2;

task drive()
{
	while(on)
	{
		motor[LeftMotor] = -leftX - leftY;
		motor[RightMotor] = -leftX + leftY;
	}
}

task manipulator()
{
	while(on)
	{
		motor[ArmMotor] = rightY;
	}
}

task main()
{
	startTask(drive);
	startTask(manipulator);

	while(on)
	{
		rightX = vexRT(Ch1);
		if(abs(rightX)<thresh){
			rightX = 0;
		}
		rightY = vexRT(Ch2);
		if(abs(rightY)<thresh){
			rightY = 0;
		}
		leftY = vexRT(Ch3);
		if(abs(leftY)<thresh){
			leftY = 0;
		}
		leftX = vexRT(Ch4);
		if(abs(leftX)<thresh){
			leftX = 0;
		}
	}
}
